const esc = value => String(value || '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

function artesanoQr({ name, slug, qrDataUri }) {
  const safeName = esc(name || 'Mi perfil de artesano');
  const safeSlug = encodeURIComponent(String(slug || ''));
  const safeQr = /^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(String(qrDataUri || '')) ? qrDataUri : '';
  const profilePath = `/artesanos/${safeSlug}`;
  const downloadPath = `${profilePath}/qr.png`;

  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#002d62"><title>Mi código QR — ${safeName} | Planeta Boricua</title><style>*{box-sizing:border-box}body{margin:0;background:#f5f5f0;color:#161616;font-family:Inter,system-ui,sans-serif}nav{background:#fff;border-bottom:3px solid #ce1126;padding:1rem 5%;display:flex;justify-content:space-between;gap:1rem}nav a{color:#002d62;text-decoration:none;font-weight:800}.wrap{max-width:760px;margin:2.5rem auto;padding:0 1rem}.card{background:#fff;border-radius:18px;padding:clamp(1.4rem,5vw,2.8rem);box-shadow:0 8px 30px #0001;text-align:center}.eyebrow{color:#ce1126;text-transform:uppercase;letter-spacing:.09em;font-size:.72rem;font-weight:900}h1{font-family:Georgia,serif;color:#002d62;font-size:clamp(2rem,6vw,3rem);line-height:1.08;margin:.55rem 0}h2{font-size:1.1rem;margin:.4rem 0 1rem;color:#333}p{color:#555;line-height:1.65}.qr{display:block;width:min(360px,100%);height:auto;margin:1.5rem auto;padding:.7rem;background:#fff;border:1px solid #d9dee8;border-radius:16px}.actions{display:flex;justify-content:center;gap:.8rem;flex-wrap:wrap;margin-top:1.5rem}.btn{display:inline-block;background:#ce1126;color:#fff;text-decoration:none;padding:.85rem 1.15rem;border-radius:8px;font-weight:850}.btn.alt{background:#fff;color:#002d62;border:1px solid #ccd3df}.tip{margin:1.6rem auto 0;padding:1rem;background:#eef5fb;border-left:4px solid #002d62;border-radius:8px;text-align:left;font-size:.9rem;max-width:570px}@media(max-width:520px){.wrap{margin:1.2rem auto}.actions{flex-direction:column}.btn{width:100%}}</style></head><body><nav><a href="/">🇵🇷 Planeta Boricua</a><a href="/feria-artesanos">Feria Digital</a></nav><main class="wrap"><section class="card"><div class="eyebrow">Feria Digital de Artesanías</div><h1>Este es tu código QR permanente</h1><h2>${safeName}</h2><p>Cuando alguien lo escanee, llegará directamente a tu perfil público en Planeta Boricua.</p>${safeQr ? `<img class="qr" src="${safeQr}" alt="Código QR del perfil de ${safeName}">` : ''}<div class="actions"><a class="btn" href="${downloadPath}" download="qr-${safeSlug}.png">⬇️ Descargar mi QR</a><a class="btn alt" href="${profilePath}">Volver a mi perfil</a></div><div class="tip"><strong>Lo puedes usar con confianza.</strong> Aunque luego actualices las fotos, la descripción o los enlaces de tu perfil, este mismo QR continuará funcionando. Puedes colocarlo en tarjetas, rótulos, empaques y publicaciones.</div></section></main></body></html>`;
}

module.exports = artesanoQr;
