const esc = value => String(value || '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

function renderExplorePB(items = []) {
  const cards = (Array.isArray(items) ? items : []).filter(item => item?.title && item?.href).slice(0, 4);
  if (!cards.length) return '';
  return `<style>
.pb-explore{border-top:1px solid #e5e7eb;margin-top:2rem;padding-top:1.7rem}.pb-explore-head{display:flex;justify-content:space-between;align-items:flex-end;gap:1rem;margin-bottom:1rem}.pb-explore h2{font-family:Georgia,serif;color:#002d62;margin:0}.pb-explore-intro{color:#666;margin:.35rem 0 0}.pb-explore-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.85rem}.pb-explore-card{display:flex;min-width:0;overflow:hidden;border:1px solid #e1e5ea;border-radius:11px;background:#fff;color:inherit;text-decoration:none;transition:transform .15s ease,box-shadow .15s ease}.pb-explore-card:hover{transform:translateY(-2px);box-shadow:0 8px 20px #002d6214}.pb-explore-image,.pb-explore-placeholder{width:112px;min-height:125px;flex:0 0 112px;object-fit:cover;background:#eef2f8}.pb-explore-placeholder{display:grid;place-items:center;font-size:2rem}.pb-explore-copy{padding:.85rem;min-width:0}.pb-explore-area{display:block;color:#ce1126;font-size:.65rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.pb-explore-title{display:block;color:#002d62;font:700 1rem/1.25 Georgia,serif;margin:.3rem 0}.pb-explore-summary{display:-webkit-box;overflow:hidden;-webkit-box-orient:vertical;-webkit-line-clamp:2;color:#666;font-size:.75rem;line-height:1.4}.pb-explore-all{display:inline-block;color:#002d62;font-weight:900;text-decoration:none;margin-top:1.05rem}.pb-explore-all:hover{text-decoration:underline}@media(max-width:680px){.pb-explore-head{align-items:flex-start;flex-direction:column}.pb-explore-grid{grid-template-columns:1fr}.pb-explore-image,.pb-explore-placeholder{width:104px;flex-basis:104px;min-height:116px}}
</style><section class="pb-explore" aria-labelledby="pb-explore-title"><div class="pb-explore-head"><div><h2 id="pb-explore-title">🇵🇷 Sigue explorando Planeta Boricua</h2><p class="pb-explore-intro">Historias, actualidad, actividades y talento de nuestra gente.</p></div></div><div class="pb-explore-grid">${cards.map(item => `<a class="pb-explore-card" href="${esc(item.href)}">${item.image ? `<img class="pb-explore-image" src="${esc(item.image)}" alt="" loading="lazy">` : '<span class="pb-explore-placeholder" aria-hidden="true">🇵🇷</span>'}<span class="pb-explore-copy"><span class="pb-explore-area">${esc(item.area)}</span><strong class="pb-explore-title">${esc(item.title)}</strong>${item.summary ? `<span class="pb-explore-summary">${esc(item.summary)}</span>` : ''}</span></a>`).join('')}</div><a class="pb-explore-all" href="/">Explora más de Planeta Boricua →</a></section>`;
}

module.exports = { renderExplorePB };
