const PHOTOS = [
  {file:'rustico-by-ivan.jpg',title:'Rústico by Iván',artisan:'José I. Cruz Jiménez',location:'San Germán, Puerto Rico',alt:'Exhibición de artesanía puertorriqueña con trabajos en madera y piezas alusivas a Puerto Rico',caption:'Exhibición de artesanía puertorriqueña con trabajos en madera y piezas alusivas a Puerto Rico.'},
  {file:'entre-maderas-vidrio-tradicion.jpg',title:'Entre Maderas, Vidrio y Tradición',artisan:'José',location:'Las Piedras, Puerto Rico',alt:'Pieza artesanal de madera con mosaico inspirado en la bandera de Puerto Rico',caption:'Pieza artesanal trabajada en madera con elementos decorativos inspirados en la bandera de Puerto Rico.'},
  {file:'crochet-couture-by-pia.jpg',title:'Crochet Couture by Pia',location:'Fajardo, Puerto Rico',alt:'Exhibición de creaciones tejidas a crochet y elaboradas a mano',caption:'Exhibición de creaciones tejidas a crochet y elaboradas a mano desde Fajardo.'},
  {file:'nudo-boricua.jpg',title:'Nudo Boricua',location:'Ceiba, Puerto Rico',alt:'Collar artesanal rojo y blanco con nudos y colgante metálico de hoja',caption:'Collar artesanal en rojo y blanco, elaborado con nudos y un colgante metálico de hoja.'},
  {file:'hecho-a-mano-by-adielys.jpg',title:'Hecho a Mano by Adielys',artisan:'Katyleida Hernández Báez',location:'Juncos, Puerto Rico',alt:'Collar artesanal de cuentas coral con detalles multicolores y colgante de hoja tropical azul',caption:'Collar artesanal de cuentas en tonos coral, con detalles multicolores y un colgante de hoja tropical azul.'},
  {file:'creations-by-carive.jpg',title:'Creations by Carive',artisan:'Carlos Rivera',location:'San José, California',alt:'Piezas artesanales de madera grabada presentadas sobre bases en el área de trabajo',caption:'Piezas artesanales elaboradas en madera, con diseños grabados y presentación sobre bases.'},
  {file:'ram-rod-creations.jpg',title:'Ram Rod Creations',artisan:'Michelle Ramirez',location:'Jacksonville, Florida',alt:'Decoración mural tejida inspirada en la bandera de Puerto Rico',caption:'Pieza artesanal tejida en rojo, blanco y azul, inspirada en la bandera de Puerto Rico.'},
  {file:'joelo-artista-puertorriqueno.jpg',title:'Joelo Artista Puertorriqueño',artisan:'Joel Rivera',location:'Arlington, Virginia',alt:'Pintura de los Tres Reyes Magos con la bandera de Puerto Rico al fondo',caption:'Obra pictórica de los Tres Reyes Magos con la bandera de Puerto Rico como elemento central del fondo.'}
];

function esc(value) {
  return String(value || '').replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[character]);
}

module.exports = function salaPrensaPB() {
  const cards = PHOTOS.map(photo => {
    const src = `/media/sala-prensa/artesanos/${photo.file}`;
    const artisan = photo.artisan ? `<span><strong>Artesano${['Katyleida Hernández Báez','Michelle Ramirez'].includes(photo.artisan) ? 'a' : ''}:</strong> ${esc(photo.artisan)}</span>` : '';
    return `<article class="photo-card"><a class="photo-link" href="${src}" target="_blank" rel="noopener"><img src="${src}" alt="${esc(photo.alt)}" loading="lazy" width="800" height="600"></a><div class="photo-copy"><h3>${esc(photo.title)}</h3><div class="facts">${artisan}<span><strong>Ubicación:</strong> ${esc(photo.location)}</span></div><p>${esc(photo.caption)}</p><p class="credit"><strong>Crédito:</strong> Cortesía de ${esc(photo.title)} / Feria Digital de Artesanos de Planeta Boricua.</p><a class="download" href="${src}" download>Descargar fotografía</a></div></article>`;
  }).join('');

  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#002d62"><title>Sala de Prensa — Planeta Boricua</title><meta name="description" content="Sala de Prensa y fotografías oficiales de la Feria Digital de Artesanos de Planeta Boricua."><meta name="robots" content="index,follow"><link rel="canonical" href="https://www.masboricuaqueunmofongo.com/sala-de-prensa"><style>
*{box-sizing:border-box}body{margin:0;background:#f5f5f0;color:#171717;font-family:Inter,system-ui,-apple-system,sans-serif}a{color:inherit}.top{background:#fff;border-bottom:3px solid #ce1126;padding:1rem 5%;display:flex;align-items:center;justify-content:space-between;gap:1rem}.top a{text-decoration:none;font-weight:850;color:#002d62}.hero{background:linear-gradient(135deg,#002d62,#001d40 65%,#ce1126);color:#fff;padding:clamp(3.5rem,8vw,6.5rem) 1.25rem}.hero-inner,.wrap{max-width:1120px;margin:auto}.kicker{font-size:.74rem;font-weight:900;letter-spacing:.13em;text-transform:uppercase;color:#ffd7dc}.hero h1{font-family:Georgia,serif;font-size:clamp(2.5rem,7vw,5rem);line-height:1;margin:.55rem 0 1rem}.hero p{max-width:720px;color:#e8eff8;font-size:clamp(1rem,2vw,1.2rem);line-height:1.65;margin:0}.wrap{padding:clamp(2rem,5vw,4rem) 1rem}.intro{display:grid;grid-template-columns:1.5fr 1fr;gap:1rem;margin-bottom:2.5rem}.panel{background:#fff;border:1px solid #e1e3e8;border-radius:14px;padding:1.3rem}.panel h2{font-family:Georgia,serif;color:#002d62;margin:.1rem 0 .7rem}.panel p,.panel li{color:#555;line-height:1.65}.panel ul{padding-left:1.2rem}.contact{border-left:5px solid #ce1126}.contact a{color:#002d62;font-weight:800}.section-head{display:flex;justify-content:space-between;align-items:end;gap:1rem;margin:2rem 0 1rem}.section-head h2{font-family:Georgia,serif;color:#002d62;font-size:clamp(1.8rem,4vw,2.6rem);margin:0}.section-head span{font-weight:800;color:#ce1126}.gallery{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1.2rem}.photo-card{background:#fff;border:1px solid #e1e3e8;border-radius:14px;overflow:hidden;box-shadow:0 7px 22px #001d400d}.photo-link{display:block;background:#e9edf2}.photo-card img{display:block;width:100%;height:auto;aspect-ratio:4/3;object-fit:cover}.photo-copy{padding:1.15rem}.photo-copy h3{font-family:Georgia,serif;color:#002d62;font-size:1.35rem;margin:0 0 .55rem}.facts{display:flex;flex-wrap:wrap;gap:.35rem 1rem;color:#555;font-size:.82rem}.photo-copy p{color:#555;line-height:1.55;font-size:.9rem}.credit{font-size:.78rem!important}.download{display:inline-block;background:#002d62;color:#fff;text-decoration:none;font-size:.8rem;font-weight:850;padding:.65rem .8rem;border-radius:7px}.usage{margin-top:2.5rem;background:#fff;border-top:5px solid #ce1126;border-radius:14px;padding:1.4rem}.usage h2{font-family:Georgia,serif;color:#002d62;margin-top:0}.usage p{color:#555;line-height:1.65}.footer{background:#002d62;color:#dbe5f2;padding:2rem 1rem;text-align:center}.footer a{color:#fff;margin:0 .4rem}.footer p{font-size:.82rem}@media(max-width:760px){.intro,.gallery{grid-template-columns:1fr}.top{align-items:flex-start}.section-head{align-items:flex-start;flex-direction:column}.photo-copy{padding:1rem}}
</style></head><body><nav class="top"><a href="/">🇵🇷 Planeta Boricua</a><a href="/feria-artesanos">Feria Digital</a></nav><header class="hero"><div class="hero-inner"><div class="kicker">Recursos para medios</div><h1>Sala de Prensa</h1><p>Información y material fotográfico oficial de la Feria Digital de Artesanos, una vitrina permanente que conecta el talento boricua de Puerto Rico y la diáspora.</p></div></header><main class="wrap"><section class="intro"><div class="panel"><h2>Material disponible</h2><p>Esta selección reúne ocho fotografías autorizadas para acompañar cobertura editorial relacionada con Planeta Boricua y su Feria Digital de Artesanos.</p><ul><li>Fotografías en formato JPG.</li><li>Pie de foto e identificación individual.</li><li>Crédito correspondiente listo para publicación.</li></ul></div><aside class="panel contact"><h2>Contacto de prensa</h2><p>Para entrevistas, información adicional o material en otro formato:</p><p><a href="mailto:masboricuaqueunmofongo@gmail.com">masboricuaqueunmofongo@gmail.com</a></p></aside></section><div class="section-head"><h2>Fotografías oficiales</h2><span>8 imágenes</span></div><section class="gallery" aria-label="Fotografías oficiales de artesanos">${cards}</section><section class="usage"><h2>Uso del material</h2><p>Las fotografías pueden utilizarse en cobertura editorial sobre Planeta Boricua y la Feria Digital de Artesanos. Al publicarlas, conserve el crédito indicado en cada imagen. Para otros usos, ediciones sustanciales o solicitudes comerciales, comuníquese primero con Planeta Boricua.</p></section></main><footer class="footer"><div><a href="/">Portal</a><a href="/feria-artesanos">Feria Digital</a><a href="/quienes-somos">Quiénes somos</a></div><p>© 2026 Planeta Boricua · Más Boricua que un Mofongo 🇵🇷</p></footer></body></html>`;
};

module.exports.PHOTOS = PHOTOS;
