module.exports = `<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Tienda Planeta Boricua | Regalos y productos de Puerto Rico</title>
<meta name="description" content="Descubre camisetas, gorras, tazas, dulces, joyería y otros productos inspirados en Puerto Rico, seleccionados por Planeta Boricua y disponibles en Amazon.">
<link rel="canonical" href="https://www.masboricuaqueunmofongo.com/tienda-boricua">
<meta property="og:type" content="website"><meta property="og:locale" content="es_PR">
<meta property="og:title" content="Tienda Planeta Boricua"><meta property="og:description" content="Una selección con sabor, orgullo y cultura de Puerto Rico.">
<meta property="og:url" content="https://www.masboricuaqueunmofongo.com/tienda-boricua">
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,700;0,800;1,700&family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<style>
*{box-sizing:border-box;margin:0;padding:0}:root{--red:#CE1126;--blue:#002D62;--ink:#131313;--mid:#626262;--paper:#f7f6f1;--white:#fff;--line:#e7e5df;--gold:#f5c842}html{scroll-behavior:smooth}body{font-family:'Inter',sans-serif;background:var(--paper);color:var(--ink);line-height:1.6}a:focus-visible{outline:3px solid var(--gold);outline-offset:3px}
.nav{background:var(--white);border-bottom:3px solid var(--red)}.nav-inner{max-width:1180px;margin:auto;padding:.75rem 1.5rem;display:flex;align-items:center;justify-content:space-between;gap:1rem}.brand{display:flex;align-items:center;gap:.65rem;color:var(--ink);text-decoration:none;font-family:'Playfair Display',serif;font-weight:800;font-size:1.15rem}.brand img{height:44px;width:auto;mix-blend-mode:multiply}.back{font-size:.8rem;color:var(--red);font-weight:700;text-decoration:none}
.hero{background:linear-gradient(125deg,rgba(0,45,98,.98),rgba(0,25,68,.95));color:#fff;position:relative;overflow:hidden}.hero:after{content:'🇵🇷';position:absolute;right:5%;bottom:-3.7rem;font-size:15rem;opacity:.055;transform:rotate(-8deg)}.hero-inner{max-width:1180px;margin:auto;padding:3.5rem 1.5rem 3rem;position:relative;z-index:1;display:grid;grid-template-columns:1.25fr .75fr;gap:3rem;align-items:center}.eyebrow{font-size:.72rem;font-weight:800;letter-spacing:.14em;text-transform:uppercase;color:var(--gold);margin-bottom:.65rem}h1{font-family:'Playfair Display',serif;font-size:clamp(2.25rem,5vw,4.25rem);line-height:1.04;max-width:760px}h1 em{color:var(--gold)}.hero-copy{color:rgba(255,255,255,.79);max-width:650px;margin:1rem 0 1.4rem;font-size:1rem}.actions{display:flex;align-items:center;gap:.8rem;flex-wrap:wrap}.button{display:inline-flex;align-items:center;justify-content:center;min-height:46px;padding:.75rem 1.2rem;border-radius:6px;text-decoration:none;font-size:.88rem;font-weight:800;transition:transform .2s,box-shadow .2s}.button:hover{transform:translateY(-2px);box-shadow:0 8px 20px rgba(0,0,0,.18)}.button-red{background:var(--red);color:#fff}.button-light{background:#fff;color:var(--blue)}.hero-note{background:rgba(255,255,255,.1);border:1px solid rgba(255,255,255,.18);border-radius:12px;padding:1.2rem}.hero-note strong{display:block;font-family:'Playfair Display',serif;font-size:1.15rem;margin-bottom:.45rem}.hero-note p{font-size:.79rem;color:rgba(255,255,255,.75)}
.disclosure{max-width:1180px;margin:0 auto;padding:.8rem 1.5rem;font-size:.76rem;color:var(--mid);text-align:center;background:#fff;border-left:1px solid var(--line);border-right:1px solid var(--line)}.disclosure a{color:var(--red);font-weight:700}.main{max-width:1180px;margin:auto;padding:3rem 1.5rem}.section-head{display:flex;align-items:end;justify-content:space-between;gap:1rem;margin-bottom:1.5rem}.section-head h2{font-family:'Playfair Display',serif;font-size:clamp(1.7rem,3vw,2.4rem);line-height:1.15}.section-head p{font-size:.88rem;color:var(--mid);max-width:480px;text-align:right}
.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:1.1rem}.card{background:#fff;border:1px solid var(--line);border-radius:12px;overflow:hidden;text-decoration:none;color:inherit;box-shadow:0 3px 12px rgba(0,0,0,.055);transition:transform .2s,box-shadow .2s,border-color .2s}.card:hover{transform:translateY(-5px);box-shadow:0 13px 30px rgba(0,0,0,.12);border-color:#d4d0c5}.card img{display:block;width:100%;aspect-ratio:4/3;object-fit:cover}.card-body{padding:1rem}.card h3{font-family:'Playfair Display',serif;font-size:1.08rem;line-height:1.2;margin-bottom:.35rem}.card p{font-size:.75rem;color:var(--mid);line-height:1.5;min-height:2.25rem}.card-link{display:block;color:var(--red);font-size:.75rem;font-weight:800;margin-top:.75rem}
.featured{margin-top:3rem;border-radius:16px;overflow:hidden;display:grid;grid-template-columns:1fr 1fr;background:var(--blue);color:#fff;box-shadow:0 14px 40px rgba(0,45,98,.18)}.featured img{width:100%;height:100%;min-height:330px;object-fit:cover}.featured-copy{padding:clamp(2rem,5vw,4rem);display:flex;flex-direction:column;align-items:flex-start;justify-content:center}.featured-copy .eyebrow{color:var(--gold)}.featured h2{font-family:'Playfair Display',serif;font-size:clamp(1.8rem,4vw,3rem);line-height:1.12;margin-bottom:.8rem}.featured p{font-size:.9rem;color:rgba(255,255,255,.75);margin-bottom:1.25rem}
.trust{margin-top:3rem;background:#fff;border:1px solid var(--line);border-radius:14px;padding:2rem;display:grid;grid-template-columns:repeat(3,1fr);gap:1.5rem}.trust-item{display:grid;grid-template-columns:auto 1fr;gap:.85rem;align-items:start}.trust-icon{width:42px;height:42px;border-radius:50%;display:grid;place-items:center;background:#edf2f8;font-size:1.2rem}.trust h3{font-size:.88rem;margin-bottom:.2rem}.trust p{font-size:.76rem;color:var(--mid)}.faq{max-width:850px;margin:3.5rem auto 0}.faq h2{text-align:center;font-family:'Playfair Display',serif;font-size:2rem;margin-bottom:1.3rem}details{background:#fff;border:1px solid var(--line);border-radius:8px;padding:1rem 1.1rem;margin-bottom:.7rem}summary{cursor:pointer;font-size:.88rem;font-weight:800}details p{padding-top:.65rem;color:var(--mid);font-size:.82rem}
.footer{background:#111;color:#fff;margin-top:4rem;border-top:4px solid var(--red)}.footer-inner{max-width:1180px;margin:auto;padding:2rem 1.5rem;display:flex;justify-content:space-between;align-items:center;gap:1rem;flex-wrap:wrap}.footer strong{font-family:'Playfair Display',serif}.footer-links{display:flex;gap:1rem;flex-wrap:wrap}.footer a{color:rgba(255,255,255,.7);font-size:.74rem;text-decoration:none}.footer a:hover{color:#fff}
@media(max-width:900px){.hero-inner{grid-template-columns:1fr}.hero-note{max-width:620px}.grid{grid-template-columns:repeat(2,1fr)}.featured{grid-template-columns:1fr}.featured img{height:340px;min-height:0}.trust{grid-template-columns:1fr}}@media(max-width:560px){.nav-inner{padding:.65rem 1rem}.brand span{display:none}.hero-inner{padding:2.5rem 1rem}.hero-note{display:none}.disclosure{padding:.8rem 1rem}.main{padding:2.3rem 1rem}.section-head{display:block}.section-head p{text-align:left;margin-top:.55rem}.grid{grid-template-columns:1fr}.card{display:grid;grid-template-columns:43% 57%}.card img{height:100%;aspect-ratio:auto}.card p{min-height:0}.featured img{height:250px}.featured-copy{padding:2rem 1.3rem}.trust{padding:1.25rem}.footer-inner{display:block}.footer-links{margin-top:1rem}}
</style>
<script type="application/ld+json">{"@context":"https://schema.org","@type":"CollectionPage","name":"Tienda Planeta Boricua","url":"https://www.masboricuaqueunmofongo.com/tienda-boricua","description":"Selección de productos inspirados en Puerto Rico y disponibles en Amazon.","isPartOf":{"@type":"WebSite","name":"Planeta Boricua","url":"https://www.masboricuaqueunmofongo.com/"}}</script>
</head><body>
<nav class="nav" aria-label="Navegación principal"><div class="nav-inner"><a href="/" class="brand"><img src="/img/pb-logo.png" alt="Planeta Boricua"><span>Planeta Boricua</span></a><a href="/" class="back">← Volver al portal</a></div></nav>
<header class="hero"><div class="hero-inner"><div><div class="eyebrow">Tienda Planeta Boricua</div><h1>Lleva a Puerto Rico <em>contigo</em></h1><p class="hero-copy">Camisetas, sabores, accesorios y regalos con orgullo boricua. Explora nuestra selección y encuentra ese detalle que te conecta con la isla.</p><div class="actions"><a href="#categorias" class="button button-red">Explorar categorías ↓</a><a href="/go/amazon-store" target="_blank" rel="sponsored noopener" class="button button-light">Ver tienda en Amazon ↗</a></div></div><aside class="hero-note"><strong>Una selección hecha con orgullo 🇵🇷</strong><p>Reunimos productos para regalar, celebrar nuestras raíces o sentir un pedacito de Puerto Rico dondequiera que estés.</p></aside></div></header>
<p class="disclosure">Como afiliado de Amazon, Planeta Boricua puede recibir una comisión por compras elegibles, sin costo adicional para ti. <a href="/afiliados-boricua">Conoce nuestra política de afiliados.</a></p>
<main class="main"><section id="categorias" aria-labelledby="categorias-title"><div class="section-head"><h2 id="categorias-title">Compra según lo que buscas</h2><p>Elige una categoría para ver la selección disponible y los detalles actuales directamente en Amazon.</p></div><div class="grid">
<a href="/go/amazon-shirts" target="_blank" rel="sponsored noopener" class="card"><img src="/img/shop/camisetas-pr.webp" alt="Camisetas inspiradas en Puerto Rico" loading="eager" decoding="async"><div class="card-body"><h3>👕 Camisetas de PR</h3><p>Diseños para llevar el orgullo boricua puesto.</p><span class="card-link">Ver selección en Amazon →</span></div></a>
<a href="/go/amazon-flags" target="_blank" rel="sponsored noopener" class="card"><img src="/img/shop/gorras-pr.webp" alt="Gorras inspiradas en Puerto Rico" loading="eager" decoding="async"><div class="card-body"><h3>🧢 Gorras de PR</h3><p>Estilos casuales con identidad de la isla.</p><span class="card-link">Ver selección en Amazon →</span></div></a>
<a href="/go/amazon-kitchen" target="_blank" rel="sponsored noopener" class="card"><img src="/img/shop/tazas-termos.webp" alt="Tazas y termos boricuas" loading="lazy" decoding="async"><div class="card-body"><h3>☕ Tazas y termos</h3><p>Para comenzar el día con sabor boricua.</p><span class="card-link">Ver selección en Amazon →</span></div></a>
<a href="/go/amazon-music" target="_blank" rel="sponsored noopener" class="card"><img src="/img/shop/cocina-criolla.webp" alt="Productos para cocina criolla" loading="lazy" decoding="async"><div class="card-body"><h3>🌿 Cocina criolla</h3><p>Esenciales para preparar nuestros sabores.</p><span class="card-link">Ver selección en Amazon →</span></div></a>
<a href="/go/amazon-books" target="_blank" rel="sponsored noopener" class="card"><img src="/img/shop/dulces-isla.webp" alt="Dulces de Puerto Rico" loading="lazy" decoding="async"><div class="card-body"><h3>🍬 Dulces de la Isla</h3><p>Antojitos que despiertan buenos recuerdos.</p><span class="card-link">Ver selección en Amazon →</span></div></a>
<a href="/go/amazon-home" target="_blank" rel="sponsored noopener" class="card"><img src="/img/shop/cuatro-patas.webp" alt="Productos boricuas para mascotas" loading="lazy" decoding="async"><div class="card-body"><h3>🐾 Boricuas de 4 patas</h3><p>Detalles con personalidad para tus mascotas.</p><span class="card-link">Ver selección en Amazon →</span></div></a>
<a href="/go/amazon-auto" target="_blank" rel="sponsored noopener" class="card"><img src="/img/shop/joyeria-boricua.webp" alt="Joyería inspirada en Puerto Rico" loading="lazy" decoding="async"><div class="card-body"><h3>💍 Joyería boricua</h3><p>Accesorios inspirados en nuestras raíces.</p><span class="card-link">Ver selección en Amazon →</span></div></a>
<a href="/go/amazon-gifts" target="_blank" rel="sponsored noopener" class="card"><img src="/img/shop/para-tu-auto.webp" alt="Accesorios boricuas para autos" loading="lazy" decoding="async"><div class="card-body"><h3>🚗 Para tu auto</h3><p>Un toque de Puerto Rico para el camino.</p><span class="card-link">Ver selección en Amazon →</span></div></a>
</div></section>
<section class="featured" aria-labelledby="merch-title"><img src="/img/shop/merch-oficial.webp" alt="Mercancía oficial de Planeta Boricua" loading="lazy" decoding="async"><div class="featured-copy"><div class="eyebrow">Más Boricua que un Mofongo</div><h2 id="merch-title">Merch oficial de Planeta Boricua</h2><p>Viste y comparte la frase que celebra nuestra identidad con humor, sabor y mucho orgullo.</p><a href="/go/amazon-merch" target="_blank" rel="sponsored noopener" class="button button-red">Ver merch oficial en Amazon ↗</a></div></section>
<section class="trust" aria-label="Cómo funciona la tienda"><div class="trust-item"><span class="trust-icon">🔎</span><div><h3>Selección Planeta Boricua</h3><p>Organizamos las opciones por categoría para ayudarte a descubrirlas más rápido.</p></div></div><div class="trust-item"><span class="trust-icon">🛒</span><div><h3>Compra segura en Amazon</h3><p>La compra, el pago y cualquier devolución se gestionan directamente con Amazon.</p></div></div><div class="trust-item"><span class="trust-icon">📦</span><div><h3>Información al día</h3><p>Confirma en Amazon el precio, la disponibilidad y la entrega para tu dirección.</p></div></div></section>
<section class="faq" aria-labelledby="faq-title"><h2 id="faq-title">Antes de comprar</h2><details><summary>¿Le compro directamente a Planeta Boricua?</summary><p>No. Los enlaces te llevan a Amazon, donde completas la compra con sus precios, métodos de pago y políticas.</p></details><details><summary>¿Todos los productos llegan a Puerto Rico y Estados Unidos?</summary><p>La disponibilidad y entrega dependen del producto, el vendedor y tu dirección. Amazon te mostrará la información vigente antes de pagar.</p></details><details><summary>¿Pagaré más por usar estos enlaces?</summary><p>No. Planeta Boricua puede recibir una pequeña comisión por compras elegibles, sin aumentar el precio que pagas.</p></details></section></main>
<footer class="footer"><div class="footer-inner"><strong>Planeta Boricua 🇵🇷</strong><div class="footer-links"><a href="/">Portal</a><a href="/quienes-somos">Quiénes somos</a><a href="/afiliados-boricua">Afiliados</a><a href="/privacidad-boricua">Privacidad</a><a href="/terminos-boricua">Términos</a></div></div></footer>
</body></html>`;
